name: Pokespeare

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v --package-path Pokespeare
    - name: Run tests
      run: swift test -v --package-path Pokespeare
