name: Pokespeare

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setup Swift 
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1.0"
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v --package-path Pokespeare
    - name: Run tests
      run: swift test -v --package-path Pokespeare
